giantswarm/cluster-cloud-director

helm/cluster-cloud-director/ci/ci-values.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

This change fixes the helm chart, Currently this repo is broken without it.

Fix trailing whitespace

---

CHANGELOG.md
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/22454

Set etcd image to retagged 3.5.4 by default

---

helm/cluster-cloud-director/Chart.yaml

This PR:
- Fix version to test if abs update `Chart.yaml` version at release time.

Fix version before release

---

CHANGELOG.md
helm/cluster-cloud-director/templates/vcdcluster.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

This PR:
- adds explicit switch for proxy enabled.
Tested locally.

add-proxy-enabled-explicit

---

.circleci/config.yml
.github/workflows/zz_generated.add-team-labels.yaml
.github/workflows/zz_generated.add-to-project-board.yaml
.github/workflows/zz_generated.check_values_schema.yaml
.github/workflows/zz_generated.create_release.yaml
.github/workflows/zz_generated.create_release_pr.yaml
.github/workflows/zz_generated.gitleaks.yaml
Makefile
Makefile.gen.app.mk
renovate.json

Align files

---

.github/pull_request_template.md
README.md
helm/cluster-cloud-director/ci/ci-values.yaml
helm/cluster-cloud-director/templates/vcdcluster.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

This PR:
- Updates the cluster chart towards commit 22af653.

update cluster charts to 22af653

---

CHANGELOG.md
helm/cluster-cloud-director/ci/ci-values.yaml
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/kubeadmconfigtemplate.yaml
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
helm/cluster-cloud-director/templates/machinedeployment.yaml
helm/cluster-cloud-director/templates/vcdmachinetemplate.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Copy of https://github.com/giantswarm/cluster-openstack/pull/120 for CAPVCD

Restructure values for better GitOps 

---

CHANGELOG.md
helm/cluster-cloud-director/files/etc/patches/kube-apiserver+json.json
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/kubeadmconfigtemplate.yaml
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
helm/cluster-cloud-director/templates/machinedeployment.yaml

Copy of  https://github.com/giantswarm/cluster-openstack/pull/114

Enable Kubeadm patches

---

.abs/main.yaml
.circleci/ct-config.yaml
.gitignore
CHANGELOG.md
Makefile.gen.app.mk
helm/cluster-cloud-director/Chart.lock
helm/cluster-cloud-director/Chart.yaml
helm/cluster-cloud-director/templates/coredns.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Copy of https://github.com/giantswarm/cluster-openstack/pull/112

Integrate cluster-shared chart lib

---

CHANGELOG.md
helm/cluster-cloud-director/files/kubelet-args
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Include:
- https://github.com/giantswarm/cluster-openstack/pull/83
- https://github.com/giantswarm/roadmap/issues/586
- https://github.com/giantswarm/cluster-openstack/pull/101
- https://github.com/giantswarm/cluster-openstack/pull/103

Sync control-plane flags with CAPO

---

CHANGELOG.md
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml

Copy of https://github.com/giantswarm/cluster-openstack/pull/82
On top of #44 for easier review

Support Encryption

---

CHANGELOG.md
helm/cluster-cloud-director/templates/kubeadmconfigtemplate.yaml
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml

This PR:
- Exposes etcd metrics for consumption by prometheus.

Expose etcd metrics

---

README.md

Update readme template

---

CHANGELOG.md
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml

Fix containerd proxy configuration

---

CHANGELOG.md
helm/cluster-cloud-director/values.schema.json

This PR:
- adds items schema for `.network.staticRoutes`
This is required for proper validation and generating a data entry form for this app (towards https://github.com/giantswarm/roadmap/issues/1181)

Add items schema for `.network.staticRoutes`

---

CHANGELOG.md
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/23306

Support extraOvdcNetworks for multi-nic

---

CHANGELOG.md
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml

This PR:
- Changes static routes setting to use a oneshot service so it persists across reboots.
Tested with `guppy-wc-xav`

use one shot service

---

CHANGELOG.md
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

add property schema for kubectlmage

---

CHANGELOG.md
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/values.schema.json

This PR:
- adds support for the diskSize feature that changes the size of the virtual disk on the nodes.
- Updates schema.

add diskSize feature and improve schema

---

CHANGELOG.md
helm/cluster-cloud-director/templates/cluster.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/24718

Add configurable cluster cr labels

---

CHANGELOG.md
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/values.schema.json

Change diskSize to diskSizeGB towards https://gigantic.slack.com/archives/C01BYMF6RN0/p1670592867807839

change diskSize to diskSizeGB for UX purposes

---

CHANGELOG.md
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml

Signed-off-by: Jiri Kremser <jiri.kremser@gmail.com>
This PR:

Include common labels for kubeadmcontrolplane.spec.machinetemplate.metadata

---

helm/cluster-cloud-director/Chart.yaml

Adding logo and icon

---

CHANGELOG.md
helm/cluster-cloud-director/files/etc/ssh/sshd_config
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/_ssh.tpl
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Towards https://github.com/giantswarm/roadmap/issues/1691

Sshd configuration for bastion concept

---

CHANGELOG.md
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/23570

Support VM naming

---

CHANGELOG.md
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/25687.
We may have to add all edge LB IPs into the SANs for our CAPVCD customer.

Add configurable certsans

---

CHANGELOG.md
helm/cluster-cloud-director/templates/machinehealthcheck.yaml

Towards https://github.com/giantswarm/giantswarm/issues/25845

Add machine health checks for worker nodes

---

CHANGELOG.md
helm/cluster-cloud-director/values.schema.json

Towards https://github.com/giantswarm/roadmap/issues/2096
This normalizes the values schema to keep subsequent PRs minimal. The change should not have any effect on validation logic.

Normalize values schema

---

CHANGELOG.md
helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml

Bump cloud provider to v0.2.5

---

README.md

Towards https://github.com/giantswarm/roadmap/issues/1072
Twin PR of https://github.com/giantswarm/cluster-vsphere/pull/41

Add notes about DNS requirement

---

CHANGELOG.md
helm/cluster-cloud-director/templates/default-helmrepository.yaml

Add default-test HelmRepository (catalog) for debugging (#124)

---

CHANGELOG.md
helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml

This PR:
- Bumps the CPI version to support K8s 1.24.

bump cpi to 0.2.6

---

CHANGELOG.md
helm/cluster-cloud-director/files/etc/kubernetes/policies/audit-policy.yaml
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml

Towards https://github.com/giantswarm/roadmap/issues/2491

Add audilog configuration

---

CHANGELOG.md
examples/giantswarm-cluster/cluster_guppy_custom-node-names.yaml
examples/giantswarm-cluster/cluster_guppy_multi-nic.yaml
examples/giantswarm-cluster/cluster_guppy_proxy.yaml
helm/cluster-cloud-director/ci/ci-values.yaml
helm/cluster-cloud-director/templates/_cluster_dns.tpl
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/_ntp.tpl
helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
helm/cluster-cloud-director/templates/cluster.yaml
helm/cluster-cloud-director/templates/coredns-helmrelease.yaml
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
helm/cluster-cloud-director/templates/vcdcluster.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/26801
Applies the standard interface for network parameters.

Unify network api

---

CHANGELOG.md
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Move `.oidc` to `.controlPlane.oidc`

---

CHANGELOG.md
README.md
examples/giantswarm-cluster/cluster_guppy_custom-node-names.yaml
examples/giantswarm-cluster/cluster_guppy_multi-nic.yaml
examples/giantswarm-cluster/cluster_guppy_proxy.yaml
helm/cluster-cloud-director/ci/ci-values.yaml
helm/cluster-cloud-director/templates/cilium-helmrelease.yaml
helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
helm/cluster-cloud-director/templates/cluster.yaml
helm/cluster-cloud-director/templates/coredns-helmrelease.yaml
helm/cluster-cloud-director/templates/default-helmrepository.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Move `.clusterDescription` to `.metadata.description`

---

CHANGELOG.md
README.md
examples/giantswarm-cluster/cluster_guppy_custom-node-names.yaml
examples/giantswarm-cluster/cluster_guppy_multi-nic.yaml
examples/giantswarm-cluster/cluster_guppy_proxy.yaml
helm/cluster-cloud-director/ci/ci-values.yaml
helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
helm/cluster-cloud-director/templates/vcdcluster.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

This PR
- moves `.userContext` to `.providerSpecific`

Move `.userContext` to `.providerSpecific`

---

CHANGELOG.md
examples/giantswarm-cluster/cluster_guppy_custom-node-names.yaml
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/values.schema.json

Move `.vmNamingTemplate` to `.providerSpecific`

---

CHANGELOG.md
helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml

To bring the fix in https://github.com/giantswarm/cloud-provider-cloud-director-app/pull/53

Update cloud-provider-cloud-director to 0.2.8

---

CHANGELOG.md
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

set default kube api port in schema

---

CHANGELOG.md

Add missing schema migration command

---

CHANGELOG.md
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml

This PR:
- adds scheduler configuration.
Tested in `leopard/staging`

add scheduler section in kcp

---

CHANGELOG.md

Fix 0.12 migration script

---

helm/cluster-cloud-director/README.md

this PR:
- adds a readme of all values.yaml options as generated by [schemadocs](giantswarm/schemadocs)

add generated schema docs

---

CHANGELOG.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/values.schema.json

This PR:
- adds Validation of nodepool name as requested [here #27306](https://github.com/giantswarm/giantswarm/issues/27306)

Add validation pattern for nodepool name

---

CHANGELOG.md

Update breaking changes for 0.11.0

---

CHANGELOG.md
helm/cluster-cloud-director/templates/cleanup-helmreleases-hook-job.yaml

Towards https://github.com/giantswarm/giantswarm/issues/27675
Copy of https://github.com/giantswarm/cluster-vsphere/pull/94

Remove leftover HelmChart CRs

---

CHANGELOG.md
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
helm/cluster-cloud-director/values.schema.json

Host entries

---

CHANGELOG.md
helm/cluster-cloud-director/files/etc/containerd/config.toml

This PR:
Fixes containerd config that is breaking in newer flatcar versions.
Same as: 
- https://github.com/giantswarm/cluster-aws/pull/421
- https://github.com/giantswarm/cluster-azure/pull/176

Fix containerd config for flatcar 3602+

---

helm/cluster-cloud-director/templates/_ignition.tpl
helm/cluster-cloud-director/templates/_ntp.tpl

ntp ignition

---

CHANGELOG.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

This PR:
- Exposes Storage Classes to cluster chart.
Towards customer requirement to change default SCs after storage changes.

Expose Storage Class properties from the CSI

---

CHANGELOG.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/cluster.yaml
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
helm/cluster-cloud-director/templates/machinedeployment.yaml
helm/cluster-cloud-director/templates/vcdcluster.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

towards https://github.com/giantswarm/giantswarm/issues/29403
- add changelog
- add preventDeletion value to metadata
- apply deletion prevention label to relevant resources

add deletion prevention label to cluster resources

---

CHANGELOG.md
helm/cluster-cloud-director/templates/cluster.yaml
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
helm/cluster-cloud-director/templates/machinedeployment.yaml
helm/cluster-cloud-director/templates/vcdcluster.yaml

See https://gigantic.slack.com/archives/C01BYMF6RN0/p1705058779470929?thread_ts=1705046980.987149&cid=C01BYMF6RN0

Fix indentation issue in preventDeletion calls

---

CHANGELOG.md
helm/cluster-cloud-director/templates/cilium-helmrelease.yaml
helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
helm/cluster-cloud-director/templates/coredns-helmrelease.yaml
helm/cluster-cloud-director/templates/netpol-helmrelease.yaml

Update Cilium to 0.19.0, CoreDNS to 1.21.0 and enable renovate on HelmReleases

---

CHANGELOG.md
helm/cluster-cloud-director/templates/cleanup-helmreleases-hook-job.yaml

towards: https://github.com/giantswarm/giantswarm/issues/29817
This PR:
- adds helm hook annotations to helmrelease cleanup job

add helm hook annotations to helmrelease cleanup job

---

CHANGELOG.md
helm/cluster-cloud-director/templates/netpol-helmrelease.yaml

disable default coredns ccnp

---

CHANGELOG.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

towards https://github.com/giantswarm/roadmap/issues/3244

Switch container registry to gsoci.azurecr.io

---

CHANGELOG.md
helm/cluster-cloud-director/templates/cleanup-helmreleases-hook-job.yaml

This PR:
- Towards alignment with https://github.com/giantswarm/cluster-azure/pull/217

Adapt cleanup hook for cluster policies

---

CHANGELOG.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

This PR:
- sets PSS to enforced by default

Enforce PSS by default

---

helm/cluster-cloud-director/templates/update-values-hook-job.yaml

kyverno checks

---

.github/pull_request_template.md
renovate.json5

This PR:
Automatically triggers E2e tests on new PRs.
Issue: https://github.com/giantswarm/giantswarm/issues/29379

Automatically trigger e2e tests on PRs.

---

CHANGELOG.md
helm/cluster-cloud-director/values.schema.json

this PR:
- allows additional values in order to support duplicates whilst the chart is being refactored

enable additional properties in the values schema to support chart refactor

---

helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml

Towards https://github.com/giantswarm/roadmap/issues/3463
Consume https://github.com/giantswarm/cloud-provider-cloud-director-app/pull/91
This must wait on ☝️ 

consume cloud provider PR

---

CHANGELOG.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/ci/test-wc-values.yaml
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/cilium-helmrelease.yaml
helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
helm/cluster-cloud-director/templates/cluster.yaml
helm/cluster-cloud-director/templates/coredns-helmrelease.yaml
helm/cluster-cloud-director/templates/default-helmrepository.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

refactor: move metadata under global values

---

CHANGELOG.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/ci/ci-values.yaml
helm/cluster-cloud-director/ci/test-wc-values.yaml
helm/cluster-cloud-director/templates/kubeadmconfigtemplate.yaml
helm/cluster-cloud-director/templates/machinedeployment.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

refactor: move nodePools under global key

---

CHANGELOG.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/ci/ci-values.yaml
helm/cluster-cloud-director/ci/test-wc-values.yaml
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
helm/cluster-cloud-director/templates/vcdcluster.yaml
helm/cluster-cloud-director/templates/vcdmachinetemplate.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

refactor: move provider specific configuration under global key

---

CHANGELOG.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/cleanup-helmreleases-hook-job.yaml
helm/cluster-cloud-director/templates/update-values-hook-job.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

refactor: move kubectlImage under internal key

---

CHANGELOG.md
examples/cluster-manifest.yaml

update example cluster manifest after chart refactoring

---

CHANGELOG.md
helm/cluster-cloud-director/templates/cilium-helmrelease.yaml
helm/cluster-cloud-director/values.schema.json

Stop setting `defaultPolicies.remove=true` in cilium-app

---

README.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/ci/ci-values.yaml
helm/cluster-cloud-director/ci/test-multiple-mirrors-with-auth-and-local-caching.yaml
helm/cluster-cloud-director/ci/test-wc-values.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

Kubernetes 1.26

---

CHANGELOG.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

kubernetes 1.27.14

---

CHANGELOG.md
helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml

cpi rollback to 1.5.0

---

CHANGELOG.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

towards https://github.com/giantswarm/giantswarm/issues/31418
I won't run CI for this as it's just a change in image name.

suffix flatcar image name with -gs

---

CHANGELOG.md
helm/cluster-cloud-director/templates/cilium-helmrelease.yaml
helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
helm/cluster-cloud-director/templates/coredns-helmrelease.yaml
helm/cluster-cloud-director/templates/netpol-helmrelease.yaml

Sue me
Too many issues while bootstrapping an MC or rolling large clusters. 

increase helmrelease retries to 50

---

CHANGELOG.md
README.md
examples/cluster-manifest.yaml
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/ci/ci-values.yaml
helm/cluster-cloud-director/ci/test-multiple-mirrors-with-auth-and-local-caching.yaml
helm/cluster-cloud-director/ci/test-wc-values.yaml
helm/cluster-cloud-director/templates/_helpers.tpl
helm/cluster-cloud-director/templates/kubeadmconfigtemplate.yaml
helm/cluster-cloud-director/templates/machinedeployment.yaml
helm/cluster-cloud-director/templates/vcdmachinetemplate.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

https://github.com/giantswarm/giantswarm/issues/31193
This PR:

Remove nodeclasses

---

CHANGELOG.md
helm/cluster-cloud-director/README.md
helm/cluster-cloud-director/ci/test-multiple-mirrors-with-auth-and-local-caching.yaml
helm/cluster-cloud-director/values.schema.json
helm/cluster-cloud-director/values.yaml

https://github.com/giantswarm/giantswarm/issues/32341
This PR:

add components.containerd

---

CHANGELOG.md
helm/cluster-cloud-director/Chart.lock
helm/cluster-cloud-director/Chart.yaml

Chart: Update `cluster` to v2.5.0.
