- CHANGELOG.md
- helm/cluster-cloud-director/templates/vcdcluster.yaml
This PR:
- fixes a validating error when the controlPlaneEndpoint properties are set to empty values.
> Fix unset control plane endpoint error

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cluster.yaml
We need this label. Otherwise, `cluster-apps-operator` ignores the cluster CR.
> Add watching label for cluster-apps-operator

- CHANGELOG.md
- README.md
- helm/cluster-cloud-director/templates/vcdcluster.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR:
- Moves vipSubnet from `cluster-api-provider-cloud-director-app` to `cluster-cloud-director` towards https://github.com/giantswarm/cluster-api-provider-cloud-director-app/pull/13
> Move vipsubnet to vcdcluster

- CHANGELOG.md
- README.md
- helm/cluster-cloud-director/Chart.yaml
- helm/cluster-cloud-director/ci/ci-values.yaml
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/templates/cluster.yaml
- helm/cluster-cloud-director/templates/kubeadmconfigtemplate.yaml
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
- helm/cluster-cloud-director/templates/machinedeployment.yaml
- helm/cluster-cloud-director/templates/vcdcluster.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR:
- Align values file with openstack.
- Removes cluster name from values and uses release name instead.
- Adds skipRDE feature to fix `clusterctl move` when API schema is not registered.
Tested helm chart in Ikoula with [CAPVCD](https://github.com/giantswarm/cluster-api-provider-cloud-director-app/pull/17).
> Adds skip rde,align values file

- CHANGELOG.md
- helm/cluster-cloud-director/templates/machinedeployment.yaml
Towards https://github.com/giantswarm/roadmap/issues/1193
See https://github.com/giantswarm/cluster-openstack/blob/main/helm/cluster-openstack/templates/machine_deployment.yaml#L12
deletion-blocker-operator observes `MachineSet` objects and it allows deletion of `VCDMachineTemplate` when there is no `MachineSet` that has a reference to that `VCDMachineTemplate`. By setting `revisionHistoryLimit` as `0`, we ask `machine-deployment-controller` to delete old `MachineSet` just after completing the updates.
> Set revisionHistoryLimit as 0

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cluster.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/13342
This PR:
- adds service priority label to cluster object.
Tested in helm template. Authorized values are "lowest", "medium", "highest".
> Add service priority label

- CHANGELOG.md
- helm/cluster-cloud-director/templates/vcdcluster.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR:
- removes default storage class from the cluster chart since it was removed from cloud init and is now installed as part of the cloud provider chart.
> remove default storage class

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/templates/kubeadmconfigtemplate.yaml
- helm/cluster-cloud-director/templates/machinedeployment.yaml
- helm/cluster-cloud-director/templates/vcdmachinetemplate.yaml
Towards https://github.com/giantswarm/giantswarm/issues/23340
We need to change two places (spec manifest + revision function) to keep the resources in sync. It is error-prone. We decided to move the templates to helpers.tpl
This PR doesn't change anything in the templates. It will change the result of revision functions in the first upgrade.
> Move specs of immutable templates to helpers.tpl

- CHANGELOG.md
- helm/cluster-cloud-director/templates/vcdcluster.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR:
- aligns proxy values with capa in values.yaml.
It's still slightly different from capa as we don't need to set `enabled` (leave empty or unset) and we allow to set `NO_PROXY`. CAPVCD includes proxy settings natively which are set in [cloud-init](https://github.com/vmware/cluster-api-provider-cloud-director/blob/1a163d92e426229dabd25bee0557d33583018488/controllers/cluster_scripts/cloud_init.tmpl#L109).
> align proxy values with capa

- CHANGELOG.md
- README.md
- helm/cluster-cloud-director/ci/ci-values.yaml
- helm/cluster-cloud-director/templates/vcdcluster.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
cluster-apps-operator only respects secretRef with refreshToken with this PR https://github.com/giantswarm/cluster-apps-operator/pull/287
We also think we shouldn't allow putting credentials to VCDCluster CR directly.
> Enforce using secretRef with refreshToken

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
- helm/cluster-cloud-director/templates/vcdcluster.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
* The `cluster-values` secret which is newly created by `cluster-apps-operator` (open PR https://github.com/giantswarm/cluster-apps-operator/pull/290) contains a valid `containerd` proxy configuration.
* CAPI is waiting, with machine-creation, once the secret got created by `cluster-apps-operator`.
* This currently work with this (https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/1) forked version of `capvcd`.
This PR:
> proxy-config injection from cluster-apps

- CHANGELOG.md
- helm/cluster-cloud-director/files/etc/gs-kube-proxy-config.yaml
- helm/cluster-cloud-director/files/etc/gs-kube-proxy-patch.sh
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
Partly copied from https://github.com/giantswarm/cluster-openstack/pull/41
Ssh part in the original PR is excluded since it is another topic. 
The logic in `gs-kube-proxy-patch.sh` and its patch was changed for CAPO while implementing ignition support. We may need to change this too. 
Node restart is also tested.
> Adapt kube-proxy configuration for monitoring

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
This PR :  **Renamed PR**
- Decouple `prekubeadmcommands` from the `containerdProxyConfig` helper function to avoid duplicate `prekubeadmcommands` in `kubeadmcontrolplane` when proxy is enabled.
> Decouple prekubeadmcommand from containerd function

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cluster.yaml
serviceDomain is used for in-cluster services and it is related to in-cluster communication.  baseDomain is mostly related to external access.
We don't set serviceDomain for other providers.
Current settings break proxy configuration since [serviceDomain is part of noProxy value](https://github.com/giantswarm/cluster-apps-operator/blob/master/service/controller/resource/clustersecret/desired.go#L165) and baseDomain shouldn't be part of noProxy value.
> Remove serviceDomain from Cluster spec

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_helpers.tpl
```
{{- define "chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```
`chart` contains the chart version and it is updated by app version. When we use it in selectors, we update selectors for each app update. This is not desired. Also some selectors are immutable and this blocks app upgrades.
See OpenStack chart https://github.com/giantswarm/cluster-openstack/blob/main/helm/cluster-openstack/templates/_helpers.tpl#L27
> Remove chart name from selector

- helm/cluster-cloud-director/values.yaml
Schema validation detected a mismatch between the `values.yaml` declaration of `nodePools: []` and the schema defining `nodePools` with type object.
Both ci-values.yaml and commented out data in values.yaml indicate that this should in fact be an object, not an array.
> Fix default nodePools value to object

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
Issue: https://github.com/giantswarm/roadmap/issues/1637
This PR:
- Adds a way to mark worker or control plane nodes with labels and taints
For control planes it's possible to add the taints, but it is not obvious from the helm's value file and the json schema. I was following the same logic as was introduced and discussed [here](https://github.com/giantswarm/cluster-aws/pull/149#discussion_r1014174884).
note: We don't have the support for machine pools at CAPVCD at the moment so it's not done exactly the same as for CAP{A,G} providers, but the result should be the same.
tested manually on guppy using helm install
- ~[ ] Update Lastpass values if required.~
> Add support for taints&labels for nodes

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_helpers.tpl
When `ssh.users` have more than 1 element, the current templating is broken.
Tested for len(ssh.users) is 0,1 and 2.
> Fix kubeadmConfigTemplateSpec for multiple ssh users

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
- helm/cluster-cloud-director/templates/registry-secret.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/24237
---
Notes for reviewer
- This is a reference implementation for https://github.com/giantswarm/rfc/pull/49. Other providers are supposed to mimic this implementation.
- Harbor will be deployed into MC and this configuration interface will allow us to add harbor as mirror registry for usual registries including its credentials. Container Solution folks confirmed it.
- The interface is as below. `containerRegistries` is a map instead of an array since map allows us to merge values for customization. Customers will be able to add their own registries.
```
connectivity:
containerRegistries:
docker.io: 
- endpoint: "registry-1.docker.io"
credentials:
username: "my_user_name"
password: "my_password"
- endpoint: …
```
> Support registry configuration for containerd

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
We move the static routes setting to `prekubeadmcommand `as opposed to `postkubeadmcommand`, otherwise it fails to download the etcd image during bootstrapping in Panamax because it requires a static route to the subnet where the http proxy lives.
> move static routes to prekubeadmcommand

- helm/cluster-cloud-director/templates/update-values-hook-job.yaml
Towards https://github.com/giantswarm/giantswarm/issues/23449
This PR fixes two things:
- It makes sure ServiceAccount Role and RoleBinding are created before the Job is created
- It makes sure they are deleted (regardless of the Job execution being successful or not)
- Note that Job resources have TTL set so they are not deleted by Helm for debugging purposes
The changelog is not updated because hooks are not yet released.
> Fix hook resource order and GC

- helm/cluster-cloud-director/templates/cleanup-helmreleases-hook-job.yaml
- helm/cluster-cloud-director/templates/update-values-hook-job.yaml
Towards https://github.com/giantswarm/giantswarm/issues/23449
https://github.com/giantswarm/cluster-cloud-director/pull/93 should be merged first ✅ 
Please read the comment at the top of the added file for description.
The changelog is not updated because previous changes are not yet released.
Verification:
```
$ k logs -n org-multi-project pawe5-cleanup-helmreleases-hook--1-tw6mm
+ kubectl get helmrelease -n org-multi-project -l giantswarm.io/cluster=pawe5 -o name
+ kubectl patch -n org-multi-project helmrelease.helm.toolkit.fluxcd.io/pawe5-cilium --type=merge -p {"metadata": {"finalizers": []}}
helmrelease.helm.toolkit.fluxcd.io/pawe5-cilium patched
+ kubectl patch -n org-multi-project helmrelease.helm.toolkit.fluxcd.io/pawe5-cloud-provider-cloud-director --type=merge -p {"metadata": …
```
> Cleanup HelmRelease CRs on deletion

- helm/cluster-cloud-director/templates/cilium-helmrelease.yaml
- helm/cluster-cloud-director/templates/cleanup-helmreleases-hook-job.yaml
- helm/cluster-cloud-director/templates/default-helmrepository.yaml
note:
this line
```
for r in $(kubectl get helmrelease -n {{ $.Release.Namespace }} -l "giantswarm.io/cluster={{ include "resource.default.name" . }}" -o name) ; do
```
([source](https://github.com/giantswarm/cluster-cloud-director/blob/60a6aa02530f7a72f94963b856077a8b39085a36/helm/cluster-cloud-director/templates/cleanup-helmreleases-hook-job.yaml#L107))
should be ok, because this particular label is [added](https://github.com/giantswarm/cluster-cloud-director/blob/60a6aa02530f7a72f94963b856077a8b39085a36/helm/cluster-cloud-director/templates/_helpers.tpl#L30) by `labels.common` helper.
> Don't put clusterLabels on HelmRe{lease,pository} CRs

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
New clusters in customer environment must be created with `enableVirtualServiceSharedIP` default value to `true`.
(until exposed in the values here).
> bump cloud provider version to v0.2.4

- CHANGELOG.md
- helm/cluster-cloud-director/templates/update-values-hook-job.yaml
Otherwise:
```
k --kubeconfig=./kubeconfigs/kind-mc-initial-leopard.kubeconfig -n org-giantswarm  logs leopard-pre-upgrade-suspend-hook-fdj68
+ kubectl patch helmrelease -n org-giantswarm leopard-cloud-provider-cloud-director --type=merge -p {"spec":{"suspend":true}}
Error from server (Forbidden): helmreleases.helm.toolkit.fluxcd.io "leopard-cloud-provider-cloud-director" is forbidden: User "system:serviceaccount:org-giantswarm:leopard-update-values-hook" cannot get resource "helmreleases" in API group "helm.toolkit.fluxcd.io" in the namespace "org-giantswarm"
```
> Fix pre-upgrade hook Job RBAC

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR:
- Makes the `VirtualServiceSharedIP` field configurable. Otherwise, clusters created in VCD environment < 10.4 _(Guppy)_ will get the [default value](https://github.com/giantswarm/cloud-provider-cloud-director-app/blob/main/helm/cloud-provider-cloud-director/values.yaml#L15) set to `true` which should be `false`.
> Make cloud provider `VirtualServiceSharedIP` configurable

- CHANGELOG.md
- helm/cluster-cloud-director/values.schema.json
Towards https://github.com/giantswarm/roadmap/issues/2096
This PR:
- fixes the schema for the `.network.ntp` object.
Working with `schemalint` and the cluster-app rule set in the future will help prevent such errors. We will bring the schema in shape to make that possible. :)
> Fix values schema for .network.ntp

- CHANGELOG.md
- helm/cluster-cloud-director/templates/default-helmrepository.yaml
When debugging someone may want to set `HelmRelease` version to something like:
```
sourceRef:
kind: HelmRepository
name: pawe2-default-test
version: 0.6.1-asdfasdfasdfasdfasdf
```
with this change `pawe2-default-test` will be installed with the helm chart and does not have to be created manually. Yes it won't be used by default but I don't think that hurts.
> Add default-test HelmRepository (catalog) for debugging

- CHANGELOG.md
- helm/cluster-cloud-director/values.schema.json
Towards https://github.com/giantswarm/roadmap/issues/2328
This PR copies the default values from `values.yaml` to `values.schema.json`, as an intermediate step.
In the next steps, the `values.yaml` file will get generated based on the schema and we are going to eliminate empty default values.
> Copy default values into schema

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_ntp.tpl
- helm/cluster-cloud-director/values.yaml
This PR adapts `values.yaml` and the template to match the values schema, where the NTP settings are placed within the `.network` object.
> Move NTP settings in values.yaml into `.network`

- CHANGELOG.md
Following up to https://github.com/giantswarm/cluster-cloud-director/pull/132
This PR adds info and a migration script to the changelog.
We have first done this in this way in cluster-aws [here](https://github.com/giantswarm/cluster-aws/blob/v0.30.0/CHANGELOG.md#0280---2023-03-23).
> Add info on breaking change and provide yq script

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
Bump cloud-provider-cloud-director app to 0.2.7
> Bump cloud-provider-cloud-director app to 0.2.7

- CHANGELOG.md
- helm/cluster-cloud-director/values.schema.json
With `schemalint` major version 2, the order of keys in `schemalint normalize` has changed to be more human-friendly. This PR updates the schema accordingly. No logical changes have been made.
Command used:
```
schemalint normalize helm/cluster-cloud-director/values.schema.json \
-o helm/cluster-cloud-director/values.schema.json \
--force
```
> Normalize values schema according to `schemalint` v2

- CHANGELOG.md
- README.md
- examples/giantswarm-cluster/cluster_guppy_custom-node-names.yaml
- examples/giantswarm-cluster/cluster_guppy_multi-nic.yaml
- examples/giantswarm-cluster/cluster_guppy_proxy.yaml
- helm/cluster-cloud-director/ci/ci-values.yaml
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR moves the .organization property to .metadata.organization
> Move `.organization` to `.metadata.organization`

- CHANGELOG.md
- helm/cluster-cloud-director/values.schema.json
Removes /includeClusterResourceSet, which is ineffectve. The implementation in cluster-shared is done in a way that it's not possible to overwrite the value. Also once effective, the setting should placed in one of the standard objects of the schema.
We removed it for the same reasons from Azure https://github.com/giantswarm/cluster-azure/pull/61 and AWS https://github.com/giantswarm/cluster-aws/pull/248
> Remove `.includeClusterResourceSet`

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
- helm/cluster-cloud-director/templates/cluster.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR
- moves the .clusterLabels value to .metadata.labels.
- Also the empty default value is removed.
- Compared to before, the key and value format are now more constrained to prevent inputs that are not valid [K8s labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set). The key pattern is not perfect to catch all invalid label keys, but it's something.
> Move `.clusterLabels` to `.metadata.labels`

- CHANGELOG.md
- helm/cluster-cloud-director/templates/vcdcluster.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR
- moves `.rdeId` to `.internal.rdeId`
- Removes the empty default from the property
> Move `.rdeId` to `.internal.rdeId`

- CHANGELOG.md
- examples/giantswarm-cluster/cluster_guppy_custom-node-names.yaml
- examples/giantswarm-cluster/cluster_guppy_multi-nic.yaml
- examples/giantswarm-cluster/cluster_guppy_proxy.yaml
- helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR
- moves `.cloudProvider` to `.providerSpecific.cloudProviderInterface`
- sets the properties in it not to be required, as we have default values for them
> Move `.cloudProvider` to `.providerSpecific.cloudProviderInterface`

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_ntp.tpl
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR
- moves `.connectivity.network.ntp` up by one level to `.connectivity.ntp`
- removes the empty default values for servers and pools
> Move `.connectivity.network.ntp` up by one level to `.connectivity.ntp`

- CHANGELOG.md
- README.md
- examples/giantswarm-cluster/cluster_guppy_proxy.yaml
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
- Moves the .proxy object into .connectivity
- Removes empty default values
- Fixes the example in README
> Move `.proxy` to `.connectivity.proxy`

- CHANGELOG.md
- README.md
- examples/giantswarm-cluster/cluster_guppy_custom-node-names.yaml
- examples/giantswarm-cluster/cluster_guppy_multi-nic.yaml
- examples/giantswarm-cluster/cluster_guppy_proxy.yaml
- helm/cluster-cloud-director/ci/ci-values.yaml
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
- helm/cluster-cloud-director/templates/machinedeployment.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
- Move `.kubernetesVersion` to `.internal.kubernetesVersion` (like in Azure and AWS)
> Move `.kubernetesVersion` to `.internal.kubernetesVersion`

- CHANGELOG.md
- helm/cluster-cloud-director/templates/vcdcluster.yaml
- helm/cluster-cloud-director/values.schema.json
This PR moves `.cluster.skipRDE` to `.internal.skipRde`. Note that the spelling is adapted to camelCase.
> Move `.cluster.skipRDE` to `.internal.skipRde`

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_ssh.tpl
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR
- Moves `.osUsers` and `.sshTrustedUserCAKeys` to the common `.connectivity.shell` object.
- Also applies a straightforward validation pattern to user name strings. Used [this document](https://systemd.io/USER_NAMES/) as a reference.
> Move `.osUsers` and `.sshTrustedUserCAKeys` to `.connectivity.shell`

- CHANGELOG.md
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
- Moves `.controllerManager` to `.internal.controllerManager`
- Makes `featureGate` a re-usable schema definition
- Harmonizes the controllerManager feature gates schema with the apiServer ones
> Move `.controllerManager` to `.internal.controllerManager`

- CHANGELOG.md
- helm/cluster-cloud-director/ci/ci-values.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR
- removes all empty default values
- changes the `.controlPlane.replicas` default value to 1 (as 0 is not a meaningful value)
- adds a default value of 1 to `.nodePools.*.replicas` (previously no default)
- adds title annotation to `.nodePools.*.replicas`
- sets `.connectivity.containerRegistries` to not required
- adds CI values for required properties in `.controlPlane.oidc` (since the empty default values got removed)
> Remove empty default values from schema, add some property defaults

- CHANGELOG.md
- helm/cluster-cloud-director/ci/ci-values.yaml
- helm/cluster-cloud-director/values.schema.json
This PR sets `"additionalProperties": false` on the objects that don't have specific configuration for additional properties. This is to catch bad user input, e.g. the use of misspelled or outdated properties.
The `.cluster-shared` property is added in order to allow use of that subchart, since each subchart injects a value with the same name into the chart values.
The properties `.managementCluster` and `.provider` are added to allow cluster-apps-operator to inject these values.
> Disallow additionalProperties on objects

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cilium-helmrelease.yaml
Found while testing https://github.com/giantswarm/cluster-cloud-director/pull/146
Otherwise:
```
Warning  FailedScheduling  81s   default-scheduler  0/5 nodes are available: 2 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 3 node(s) had untolerated taint {node.cloudprovider.kubernetes.io/uninitialized: true}. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling.
```
See more details in Slack: https://gigantic.slack.com/archives/C01F7T2MNRL/p1687373676074119
> Add tolerations for hubble rely and ui

- CHANGELOG.md
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
https://github.com/giantswarm/klingel/issues/91
This PR:
- Set value for terminated pod gc threshold to be consistent with vintage
> Set value for terminated pod gc threshold to be consistent with vintage

- CHANGELOG.md
- helm/cluster-cloud-director/README.md
- helm/cluster-cloud-director/files/etc/containerd/config.toml
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/templates/containerd-config-secret.yaml
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
- helm/cluster-cloud-director/templates/registry-secret.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR:
- Consolidate the full `config.toml` configuration file for containerd into a single file to address [#1737](https://github.com/giantswarm/roadmap/issues/1737)
@erkanerol as discussed in https://gigantic.slack.com/archives/C01BYMF6RN0/p1689847741604689?thread_ts=1689844311.988129&cid=C01BYMF6RN0 can you verify it when using the `credentials and mirrors` configurations ? the structure of values has not changed for those settings
> Consolidate containerd config.toml in single file

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_helpers.tpl
towards https://github.com/giantswarm/giantswarm/issues/27037
This PR:
- adds user `nobody` to group `root` to allow node-exporter to access the host's filesystem. 
this aligns with CAPA.
> add user nobody to root group to enable node-exporter's filesystem collection to access the host filesystem

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cleanup-helmreleases-hook-job.yaml
- helm/cluster-cloud-director/templates/netpol-helmrelease.yaml
issue: https://github.com/giantswarm/roadmap/issues/2815
This pr: installs network-policies-app as a HelmRelease that will effectively lock all the communication to `giantswarm` and `kube-system` namespaces
> Lock everything by default in giantswarm and kube-system namespaces

- CHANGELOG.md
- helm/cluster-cloud-director/README.md
- helm/cluster-cloud-director/templates/cilium-helmrelease.yaml
- helm/cluster-cloud-director/templates/cleanup-helmreleases-hook-job.yaml
- helm/cluster-cloud-director/templates/netpol-helmrelease.yaml
- helm/cluster-cloud-director/templates/update-values-hook-job.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
Pods from the helmrelease hook jobs fails to reach the K8s API.
I needed to add an extra label as a label named `job-name` fails to get picked up by the endpoint selector.
https://gigantic.slack.com/archives/CLPMFRVU6/p1706112803756279?thread_ts=1706112616.784229&cid=CLPMFRVU6
This PR:
> Add CNPs to hook jobs

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cleanup-helmreleases-hook-job.yaml
- helm/cluster-cloud-director/templates/update-values-hook-job.yaml
This PR:
- only creates Cilium resources if Cilium CRDs exist
This is necessary because the bootstrap cluster (kind, vcluster) doesn't run Cilium, so chart installation fails.
> Only create Cilium resources if Cilium CRDs exist

- CHANGELOG.md
- helm/cluster-cloud-director/README.md
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR:
- bumps kubectl image to 1.25.15 to avoid version skew with cluster version.
> Bump kubectl image to 1.25.15

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cilium-helmrelease.yaml
- helm/cluster-cloud-director/templates/netpol-helmrelease.yaml
Signed-off-by: Matias Charriere <matias@giantswarm.io>
This PR:
- Remove default policies from cilium-app
- Install DNS policies from network-policies-app
Towards https://github.com/giantswarm/roadmap/issues/3261
> remove default-policies and enable DNS policies

- CHANGELOG.md
- README.md
- helm/cluster-cloud-director/README.md
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This PR:
- Sets the default `nodeClass` and `nodePool` in schema/values.
The customer sets these values so they'll be overwritten but it will be helpful for E2E tests.
Alignment with https://github.com/giantswarm/cluster-vsphere/blob/main/helm/cluster-vsphere/values.yaml
- Sets `Flatcar` as the default OS.
- Sets Kubernetes version `1.25.16` by default
- Removes defaulted disk size. Otherwise it would break the FS on VMs deployed from a template with a disk >30GB
The [method](https://github.com/giantswarm/giantswarm/issues/30386) to set default nodeclass/nodepool might change in the future when we move to using the cluster shared chart.
> Set a default nodeclass, nodepool, Flatcar and kubernetesVersion

- helm/cluster-cloud-director/templates/_ignition.tpl
> fix broken vmtoolsd path

- CHANGELOG.md
- README.md
- helm/cluster-cloud-director/README.md
- helm/cluster-cloud-director/templates/_ignition.tpl
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/30385
This PR:
- Updates machine template to newer Flatcar version with includes teleport v15.1.7 binary. 
**WARNING: This will roll CP and worker nodes.**
> Update machine template: `flatcar-stable-3815.2.1-kube-v1.25.16`

- CHANGELOG.md
- helm/cluster-cloud-director/README.md
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/3101
This PR:
- Enables teleport by default
> Enable teleport by default

- CHANGELOG.md
- helm/cluster-cloud-director/README.md
- helm/cluster-cloud-director/ci/test-wc-values.yaml
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/templates/cilium-helmrelease.yaml
- helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
- helm/cluster-cloud-director/templates/cluster.yaml
- helm/cluster-cloud-director/templates/coredns-helmrelease.yaml
- helm/cluster-cloud-director/templates/default-helmrepository.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
Notes: 
- it's not possible to test this using the e2e CI tests because the [test cluster values](https://github.com/giantswarm/cluster-standup-teardown/blob/main/pkg/clusterbuilder/providers/capvcd/values/cluster_values.yaml) have not been updated yet (and cannot be updated until the chart refactoring is complete and released). Running the CI tests locally with manually updated values passes though:
```
Ran 18 of 27 Specs in 2644.239 seconds
SUCCESS! -- 18 Passed | 0 Failed | 0 Pending | 9 Skipped
PASS
Ginkgo ran 1 suite in 44m12.717261703s
Test Suite Passed
```
- the [documentation validation checks](https://github.com/giantswarm/cluster-cloud-director/actions/runs/8991262702/job/24698451089?pr=296) are showing as failed, but …
> refactor: move metadata under global key

- CHANGELOG.md
- README.md
- helm/cluster-cloud-director/templates/_helpers.tpl
- helm/cluster-cloud-director/templates/_ignition.tpl
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
If a node reboots, the routes aren't installed as it happens in kubeadm.
It should be a unit in ignition. Context: https://gigantic.slack.com/archives/C02EVLE9W/p1714374192860579
I had a race condition issue when using a dedicated networkd unit so I moved the ip route add commands to the script that sets up networking.
(Rework of https://github.com/giantswarm/cluster-cloud-director/pull/293)
> move static route to unit

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_ignition.tpl
Sometimes the first static route would not be added. Most likely because `systemd-networkd` took a bit longer to restart.
I added a 3 seconds wait which seems to fix the issue.
After rolling it to `glasgow` I haven't observed the issue.
> Fix race condition with networkd restart

- CHANGELOG.md
- helm/cluster-cloud-director/README.md
- helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
This pr removes our ability to set etcd images (and coredns which wasn't used like that anyways). This means it will be handled automatically by kubeadm.
This also aligns with our cloud providers.
https://gigantic.slack.com/archives/CLPMFRVU6/p1712831360621509?thread_ts=1712831054.292869&cid=CLPMFRVU6
> Remove etcd and dns images from kubeadmcontrolplane

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_ignition.tpl
- helm/cluster-cloud-director/values.schema.json
Because we can't set the routes as networkd units, we use imperative commands (not permanent routes). Meaning if `systemd-networkd` goes down for some reason, the routes will be lost when it is started again. This happened where resource exhaustion caused networkd to crash.
Here we use a combination of systemd flags:
- `BindsTo=systemd-networkd.service` : Stop `set-static-routes` if `systemd-networkd` goes down.
- `After=systemd-networkd.service` : Won't start `set-static-routes` if `systemd-networkd` and `set-networkd-units` is down.
- `Upholds=set-static-routes.service` : Start `set-static-routes` when `systemd-networkd` starts.
Note that the E2E tests don't test for this.
Scenarios manually tested:
- Create WC.
- Observe the routes are there.
- Restart networkd and observe the routes …
> Static routes bindsto networkd unit

- CHANGELOG.md
- helm/cluster-cloud-director/README.md
- helm/cluster-cloud-director/ci/test-multiple-mirrors-with-auth-and-local-caching.yaml
- helm/cluster-cloud-director/files/etc/containerd/config.toml
- helm/cluster-cloud-director/values.schema.json
- helm/cluster-cloud-director/values.yaml
Towards: https://github.com/giantswarm/roadmap/issues/3460
Related to: https://github.com/giantswarm/cluster/pull/178
> Support local registry caches

- CHANGELOG.md
- helm/cluster-cloud-director/templates/_ignition.tpl
Fixes a race condition where the `kubeadm` service would fail because it was trying to pull the `kube-apiserver` image before the static routes were installed.
> Run kubeadm after static routes

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cilium-helmrelease.yaml
Upstream marked 'strict' as deprecated in 1.15 and will remove it completely in 1.16.
Signed-off-by: Matias Charriere <matias@giantswarm.io>
Towards https://github.com/giantswarm/giantswarm/issues/31353
>  Set cilium kubeProxyReplacement to 'true'

- CHANGELOG.md
- helm/cluster-cloud-director/templates/cloud-provider-cloud-director-helmrelease.yaml
cloud-provider-cloud-director helm chart uses now the the version which is set in the release: https://github.com/giantswarm/releases/pull/1484/files#diff-3376c10a60e0b85fc9f8d0767f87b792e8381b0122f6298be0e0038419f17c48R27-R28
> Use helm release version for cpcd from releases
